-- 一期生
require "extensions.sakamichi.HiraganaKeyakizaka46.IKiSei.ShihoKato"
require "extensions.sakamichi.HiraganaKeyakizaka46.IKiSei.MireiSasaki"
require "extensions.sakamichi.HiraganaKeyakizaka46.IKiSei.KyokoSaito"
require "extensions.sakamichi.HiraganaKeyakizaka46.IKiSei.AyakaTakamoto"
require "extensions.sakamichi.HiraganaKeyakizaka46.IKiSei.KumiSasaki"
require "extensions.sakamichi.HiraganaKeyakizaka46.IKiSei.SarinaUshio"
require "extensions.sakamichi.HiraganaKeyakizaka46.IKiSei.MaoIguchi"
require "extensions.sakamichi.HiraganaKeyakizaka46.IKiSei.MemiKakizaki"
require "extensions.sakamichi.HiraganaKeyakizaka46.IKiSei.ManaTakase"
-- require "extensions.sakamichi.HiraganaKeyakizaka46.IKiSei.MeiHigashimura"
-- require "extensions.sakamichi.HiraganaKeyakizaka46.IKiSei.NeruNagahama"
-- require "extensions.sakamichi.HiraganaKeyakizaka46.IKiSei.YuukaKageyama"
-- 二期生
-- require "extensions.sakamichi.HiraganaKeyakizaka46.NiKiSei.HinaKawata"
-- require "extensions.sakamichi.HiraganaKeyakizaka46.NiKiSei.HiyoriHamagishi"
-- require "extensions.sakamichi.HiraganaKeyakizaka46.NiKiSei.MikuKanemura"
-- require "extensions.sakamichi.HiraganaKeyakizaka46.NiKiSei.KonokaMatsuda"
-- require "extensions.sakamichi.HiraganaKeyakizaka46.NiKiSei.SuzukaTomita"
-- require "extensions.sakamichi.HiraganaKeyakizaka46.NiKiSei.AkariNibu"
-- require "extensions.sakamichi.HiraganaKeyakizaka46.NiKiSei.NaoKosaka"
-- require "extensions.sakamichi.HiraganaKeyakizaka46.NiKiSei.MihoWatanabe"
-- require "extensions.sakamichi.HiraganaKeyakizaka46.NiKiSei.ManamoMiyata"
-- 三期生
-- require "extensions.sakamichi.HiraganaKeyakizaka46.SanKiSei.HinanoKamimura"
-- SP
-- require "extensions.sakamichi.HiraganaKeyakizaka46.SP.KumiSasaki"
