require "extensions.sakamichi.AutisticGroup.Staff.YasushiAkimoto"
require "extensions.sakamichi.AutisticGroup.Staff.NoburuOkada"
require "extensions.sakamichi.AutisticGroup.Staff.MinoruKamiyama"
require "extensions.sakamichi.AutisticGroup.Staff.OsamuShitara"
require "extensions.sakamichi.AutisticGroup.Staff.YukiHimura"
require "extensions.sakamichi.AutisticGroup.Staff.YoshioKonno"
require "extensions.sakamichi.AutisticGroup.Staff.YoheiFurukawa"
require "extensions.sakamichi.AutisticGroup.Staff.AmonNijihiko"
require "extensions.sakamichi.AutisticGroup.Staff.MitsuharuSato"
require "extensions.sakamichi.AutisticGroup.Staff.ManabuKishi"
require "extensions.sakamichi.AutisticGroup.Staff.MasayasuWakabayashi"
require "extensions.sakamichi.AutisticGroup.Staff.ToshiakiKasuga"

require "extensions.sakamichi.AutisticGroup.Original.MomomaiOozono"
require "extensions.sakamichi.AutisticGroup.Original.ShuukanBunshun"
require "extensions.sakamichi.AutisticGroup.Original.TanOshi"
require "extensions.sakamichi.AutisticGroup.Original.WuNai"
require "extensions.sakamichi.AutisticGroup.Original.Yasuo"

require "extensions.sakamichi.AutisticGroup.Alias.ErikaSouda"
require "extensions.sakamichi.AutisticGroup.Alias.HinaKawaai"
require "extensions.sakamichi.AutisticGroup.Alias.NaoYumiki"
require "extensions.sakamichi.AutisticGroup.Alias.YuiKashiwagi"
