require "extensions.sakamichi.Hinatazaka46.IKiSei.ShihoKato"
require "extensions.sakamichi.Hinatazaka46.IKiSei.MireiSasaki"
require "extensions.sakamichi.Hinatazaka46.IKiSei.KyokoSaito"
require "extensions.sakamichi.Hinatazaka46.IKiSei.AyakaTakamoto"
require "extensions.sakamichi.Hinatazaka46.IKiSei.KumiSasaki"
require "extensions.sakamichi.Hinatazaka46.IKiSei.SarinaUshio"
require "extensions.sakamichi.Hinatazaka46.IKiSei.MaoIguchi"
require "extensions.sakamichi.Hinatazaka46.IKiSei.MemiKakizaki"
require "extensions.sakamichi.Hinatazaka46.IKiSei.ManaTakase"
require "extensions.sakamichi.Hinatazaka46.IKiSei.MeiHigashimura"
require "extensions.sakamichi.Hinatazaka46.IKiSei.YuukaKageyama"

require "extensions.sakamichi.Hinatazaka46.NiKiSei.HinaKawata"
require "extensions.sakamichi.Hinatazaka46.NiKiSei.HiyoriHamagishi"
require "extensions.sakamichi.Hinatazaka46.NiKiSei.MikuKanemura"
require "extensions.sakamichi.Hinatazaka46.NiKiSei.KonokaMatsuda"
require "extensions.sakamichi.Hinatazaka46.NiKiSei.SuzukaTomita"
require "extensions.sakamichi.Hinatazaka46.NiKiSei.AkariNibu"
require "extensions.sakamichi.Hinatazaka46.NiKiSei.NaoKosaka"
require "extensions.sakamichi.Hinatazaka46.NiKiSei.MihoWatanabe"
require "extensions.sakamichi.Hinatazaka46.NiKiSei.ManamoMiyata"

require "extensions.sakamichi.Hinatazaka46.SanKiSei.MarieMorimoto"
require "extensions.sakamichi.Hinatazaka46.SanKiSei.HinanoKamimura"
require "extensions.sakamichi.Hinatazaka46.SanKiSei.MikuniTakahashi"
require "extensions.sakamichi.Hinatazaka46.SanKiSei.HaruyoYamaguchi"