require "extensions.sakamichi.package"

yinni_hide = sgs.General(Sakamichi, "yinni_hide", "Sakurazaka46", 0, true, true, true)

require "extensions.sakamichi.Sakurazaka46.IKiSei.YuiKobayashi"
require "extensions.sakamichi.Sakurazaka46.IKiSei.AoiHarada"
require "extensions.sakamichi.Sakurazaka46.IKiSei.MinamiKoike"
require "extensions.sakamichi.Sakurazaka46.IKiSei.FuyukaSaito"
require "extensions.sakamichi.Sakurazaka46.IKiSei.RikaOzeki"
require "extensions.sakamichi.Sakurazaka46.IKiSei.RisaWatanabe"
require "extensions.sakamichi.Sakurazaka46.IKiSei.AkaneMoriya"
require "extensions.sakamichi.Sakurazaka46.IKiSei.RinaUemura"
require "extensions.sakamichi.Sakurazaka46.IKiSei.MizuhoHabu"
require "extensions.sakamichi.Sakurazaka46.IKiSei.YukaSugai"
require "extensions.sakamichi.Sakurazaka46.IKiSei.RikaWatanabe"

require "extensions.sakamichi.Sakurazaka46.NiKiSei.RenaMoriya"
require "extensions.sakamichi.Sakurazaka46.NiKiSei.MarinoKousaka"
require "extensions.sakamichi.Sakurazaka46.NiKiSei.YumikoSeki"
require "extensions.sakamichi.Sakurazaka46.NiKiSei.ReiOozono"
require "extensions.sakamichi.Sakurazaka46.NiKiSei.HikaruMorita"
require "extensions.sakamichi.Sakurazaka46.NiKiSei.RinaMatsuda"
require "extensions.sakamichi.Sakurazaka46.NiKiSei.YuiTakemoto"
require "extensions.sakamichi.Sakurazaka46.NiKiSei.RikoMatsudaira"
require "extensions.sakamichi.Sakurazaka46.NiKiSei.HikariEndo"
require "extensions.sakamichi.Sakurazaka46.NiKiSei.KarinFujiyoshi"
require "extensions.sakamichi.Sakurazaka46.NiKiSei.KiraMasumoto"
require "extensions.sakamichi.Sakurazaka46.NiKiSei.TenYamasaki"
require "extensions.sakamichi.Sakurazaka46.NiKiSei.RiraInoue"
require "extensions.sakamichi.Sakurazaka46.NiKiSei.HonoTamura"
require "extensions.sakamichi.Sakurazaka46.NiKiSei.AkihoOnuma"